import { KeyRound, AlertTriangle } from "lucide-react";
import ResetPasswordForm from "../../components/ResetPasswordForm";
import AuthPageHeader from "../../components/AuthPageHeader";
import AuthShell from "../../components/AuthShell";

export const metadata = {
  title: "Redefinir senha",
};

// This exact path (`/auth/reset-password`) is generated by the backend's
// buildAdvancedSettings/buildEmailTemplates (src/auth/config.ts) as the
// `email_reset_password` link and the reset email's action URL — it must
// match verbatim, it is not a free choice like the login/register slugs.
export default async function ResetPasswordPage({
  searchParams,
}: {
  searchParams: Promise<{ code?: string }>;
}) {
  const { code } = await searchParams;

  if (!code) {
    return (
      <AuthShell>
        <AuthPageHeader
          icon={AlertTriangle}
          title="Link inválido"
          subtitle="Este link de redefinição não é válido ou já expirou."
          tone="error"
        />
        <div className="flex flex-col gap-3">
          <span className="font-medium text-vh-13-5 font-manrope text-vh-muted">
            Solicite uma nova redefinição de senha para continuar.
          </span>
        </div>
      </AuthShell>
    );
  }

  return (
    <AuthShell>
      <AuthPageHeader
        icon={KeyRound}
        title="Redefinir senha"
        subtitle="Escolha uma nova senha para sua conta."
      />
      <ResetPasswordForm code={code} />
    </AuthShell>
  );
}
