import ResetPasswordForm from "../../components/ResetPasswordForm";

export const metadata = {
  title: "Redefinir senha",
};

// This exact path (`/auth/reset-password`) is generated by the backend's
// buildAdvancedSettings/buildEmailTemplates (src/auth/config.ts) as the
// `email_reset_password` link and the reset email's action URL — it must
// match verbatim, it is not a free choice like the login/register slugs.
export default async function ResetPasswordPage({
  searchParams,
}: {
  searchParams: Promise<{ code?: string }>;
}) {
  const { code } = await searchParams;

  return (
    <section className="max-w-125 my-0 mx-auto py-12 px-6 w-full">
      <h1 className="mt-0 mx-0 mb-2 font-bold text-vh-34 font-space-grotesk">
        Redefinir senha
      </h1>
      <p className="mt-0 mx-0 mb-7.5 font-medium text-vh-14 font-manrope text-vh-muted">
        Escolha uma nova senha para sua conta.
      </p>
      {code ? (
        <ResetPasswordForm code={code} />
      ) : (
        <div className="bg-vh-card border border-vh-border rounded-2xl p-6 flex flex-col gap-3">
          <span className="font-semibold text-vh-13-5 font-manrope text-red-400">
            Link inválido ou expirado. Solicite uma nova redefinição de senha.
          </span>
        </div>
      )}
    </section>
  );
}
